INHERIT: ../base.yml
site_name: Apuntes 2
site_url: https://crispy-carnival-8f8f6875.pages.github.io/docs/apuntes2
site_dir: ../../docs/apuntes2
plugins:
  - search:
      lang: es
  - with-pdf:
      author: Equipo educativo de ciberseguridad del IES Rafael Alberti
      copyright: CC BY-SA 4.0
      cover: true
      cover_logo: assets/logo-alberties.png
      cover_title: Apuntes 2
      cover_subtitle: Me gusta este subtítulo
      toc_title: Tabla de contenidos
      output_path: pdf/apuntes2.pdf